### ISSUE TITLE
SRD Creatures?

### ISSUE THREAD

**Issue by stories-with-dice** [Genii-Locorum/brp#12]
Hey,

Any plans to add the SRD Creatures?

Any way I could help?

**Comment by Genii-Locorum** [comment]
I want to.  So far I've focussed on Characters and the game mechanics although due to other commitments (pesky real life) I've not looked at BRP for a month or two (I will get back to it - April or May time, work depending).

The two things I need first is the data structure for a creature/NPC and then a layout for a creature/NPC sheet.  I'm easy whether its one to cover both types or separate sheets.

My though was to have each creature be a distinct culture - drag and drop the culture on to a blank creature and voila it becomes a goblin, dragon, zombie whatever.

I'd be happy to have help on any of the BRP development.  If you wanted to start something I'd probably think about drafting a data model.  Let me know what you can help with and happy to take a chat off line (at least from this area) to work out the art of the possible.

And thank you for the offer to help out, it's appreciated

**Comment by stories-with-dice** [comment]
Hey,

I'm not that great with JS, so not sure I can help with the coding part (especially something as fundamental as a data model).

I'm not clear why a new data model is needed for NPCs / Creatures. They seem to have the same stat fields.

I was thinking of simply using the PC sheet to create and store the monsters in a Compendium.

**Comment by Genii-Locorum** [comment]
No worries about the JS side I'm happy to do the coding and any help with design or input very gratefully received.  

The differences in data model come from how I want the creature to operate.  For example - for characters I link weapon to skill(s) so when you use the weapon it looks for the relevant skill and pulls the score across.

For creatures (and with an eye to maybe having a stat block importer) weapons are likely to have the skill chance embedded in the item.  Or I may want to have armour values entered by the GM rather than calculated from items work.   So data models start to vary between Characters and Creatures etc.  I havent really started looking at NPCs to work out how much needs to change to make creation of creatures/NPCs quick (and the answer may be its very little)

I'm also thinking about dice for stats for non-humans - for characters I was thinking of using culture in for stats dice (e.g. 3D6) but for NPCs perhaps that's built in as a standard creature.

All stuff I need to think about to make it easy for GM to populate and run lots of creatures.  I'm back in April and hoping to find time to get back to BRP.  

If before then you want to have a think about the structures/operation or what info is needed for creatures I'm happy to code it and then maybe we can start populating it  - more than happy to share workload :-)  

Cheers

Simon

**Comment by Genii-Locorum** [comment]
Morning - sorry I've been absent for so long - but I'm back and have some time.   I've got four things on my workstack at the moment for BRP (but this could change) - 

Allegiances
Passions
NPC Sheet
Creatures

The NPC Sheet will be a foundation for Creatures which (at the moment) I'm thinking of building off Cultures

Call of Cthulhu for Foundry has a really nice implementation whereby you have the dice for stats etc and then you get options to either roll the dice to auto generate or you can use "average" values.   I was thinking of doing something similar.

So watch this space and once I've got a plan I will reach out - any help in creating the actual creatures once I've built the code would be great.

Cheers

Simon

**Comment by Genii-Locorum** [comment]
@stories-with-dice 

I've just released V15 of BRP with NPCs added - so if you are still interested in creating a Bestiary then please let me know.

I think the easiest way would be to create a bunch of npcs and then put them in a module.  If you want to message me we can look at what you're comfortable doing and how to make it available to others.

Cheers

Simon

**Comment by stories-with-dice** [comment]
Hey @Genii-Locorum 

This sounds great. I appreciate your efforts! 

Unfortunately life happened and I can't really commit to this for the time being.

**Comment by Lockbox313** [comment]
Is there another version of the SRD ?  Version  1.0 that is available from the Chaosium website has one creature a Bear.

**Comment by Genii-Locorum** [comment]
@stories-with-dice  - hey no worries and completely understandable.  I hope life sorts itself out for you.

As mentioned by @Lockbox313  - is there a particular SRD you were thinking of to use to populate a bestiary?

Cheers

Simon

**Comment by stories-with-dice** [comment]
There are two SRDs online:

- https://bruge.us/rules/srd/ (select "Creatures" from the menu)
- https://storieswithdice.com/brp_srd/11.-Creatures (this one is mine)

AFAIK, the SRD contents are all ORC Content.

**Comment by Genii-Locorum** [comment]
This is now being worked on = thank you to Crys.

**Comment by stories-with-dice** [comment]
Cool! I looked into it a few days ago and I didn't see a way to edit the NPC when I added one.

**Comment by Genii-Locorum** [comment]
Added in 12.1.31

@stories-with-dice - on the NPC sheet there's now an icon for "Base Stats" where you can enter formula.  There are also some buttons to roll "Random" or "Average" stats.  In addition there are some game settings to control the default position when dragging an unlinked NPC with some Base Stats populated so they can auto roll when added to a scene.  I need to write up some instructions for the Wiki but the functionality is now here.

The actual creatures (thanks to Crys) are appearing in the BRP module - they are not all there yet and we will add more in due course.

Hope this is what you were after but if it needs more features please do shout.

**Comment by Cosmic-Cocoa** [comment]
Hi all. I'm Crys. I've been working on the SRD creatures. 

Currently all Fantasy Creatures, Summoned Creates, and Science Fiction Creatures plus a few NPCs from the NPC catalogue are in the BRP module. As of last night I had finished the NPC Catalogue. I'm working on Natural Animals now. I just wanted to invite you, particularly @stories-with-dice and @Lockbox313 since I've already been chatting quite a bit with Genii-Locorum, to let me know if I've made any typos or errors or if there's a better way to handle something on the NPC data entry.

As an aside, I have included relevant rules for individual creature attacks in the GM Notes tab of the weapon on their sheet.
So you can see those if you open the weapon item:
![image](https://github.com/user-attachments/assets/ed06928d-07a2-4f6c-ae35-fe00eabd6090)

Anyway, that was it, just thought I'd invite feedback from y'all since you'd asked about this before.

Also, thank you @stories-with-dice, for your SRD webpage. I've referenced that almost as much as the book itself in creating this. It's nice to have multiple sections open in different tabs! <3

**Comment by Lockbox313** [comment]
Do  they need imported because when I drag something out  to the Actors tab I get

> actor.mjs:465 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'brpidFlag')
> [Detected 1 package: system:brp(12.1.32)]
>     at actor.mjs:465:70
>     at Actors.filter (foundry-esm.js:5010:14)
>     at BRPActor.create (actor.mjs:465:42)
>     at ActorDirectory._createDroppedEntry (foundry.js:74057:33)
>     at ActorDirectory._handleDroppedEntry (foundry.js:73516:28)

System 12.1.32 BRP UGE Compedium 1.0.3

**Comment by Lockbox313** [comment]
Actually importing throws the same error

**Comment by Genii-Locorum** [comment]
Is this a particular creature or a lot of them?

**Comment by Lockbox313** [comment]
The Centaur. Hang on I will try some more

**Comment by Genii-Locorum** [comment]
Centaur was working for me.

Can you check the item in the compendium - does it have a BRPID?

Can you drag the item to the canvas directly - does it have the same problem?

**Comment by Lockbox313** [comment]
Dragged or imported  individually they all throw the errors.  But Import All Content does not throw any errors.

**Comment by Lockbox313** [comment]
Dragging to the canvas throws the same error

**Comment by Lockbox313** [comment]
The one's I checked in the compendiums have ID's.

**Comment by Genii-Locorum** [comment]
Any old actors in game without BRPIDs?

**Comment by Lockbox313** [comment]
Let me check I ran the macro a bunch of time but you never know.

**Comment by Genii-Locorum** [comment]
No worries.  I'll think about some trouble shooting code to try and avoid this for others.  Essentially all I'm doing is trying to prevent multiple NPCs being created when dropped to the canvas directly from the compendium (multiple tokens is fine, just didnt want 27 copies of Goblins in the game.actors  :-)
