### ISSUE TITLE
I'm unable to make any rolls beside regular rolls

### ISSUE THREAD

**Issue by LeonxnoeL** [Genii-Locorum/brp#16]
The dialog box for opposed/combined/cooperative rolls never pop up when I select these types. Instead, this shows up in the console instead so I figured it might help you troubleshoot it:

![image](https://github.com/Genii-Locorum/brp/assets/34650669/2b05b88c-187e-4ad9-a2d4-017e62bbf9eb)

**Comment by Genii-Locorum** [comment]
Thanks for reporting this.  What version of Foundry and BRP are you using?

**Comment by LeonxnoeL** [comment]
> Thanks for reporting this. What version of Foundry and BRP are you using?

I'm using the latest BRP version 12.1.17 and Foundry version 11 stable build 307!

**Comment by LeonxnoeL** [comment]
I'm something of a programmer myself but I have never really touched javascript/css/html... I have only fiddled a little with kotlin here and there but I'm having fun trying to make sense out of this issue xD. Seems to be something related to this OTHER from CHAT_MESSAGE_STYLES but I can't find where those are declared at all.

Also, if it helps, I am using the Dice So Nice! module and another module called Wooden UI which changes some of the UI, not sure if those could interfere or not.

**Comment by LeonxnoeL** [comment]
Also, to clarify, resistances rolls are working! It seems only opposed/combined/cooperative rolls refuse to open.

**Comment by Genii-Locorum** [comment]
That really helps - and I know what the problem is (or rather, what my mistake was).  I've said this version of BRP is valid for version 11 - when I should have said V12 only.

You're spot on with the CHAT_MESSAGE_STYLES "OTHER", it's something that changed from V11 to V12 (they are defined in Foundry iteself rather than this system).  Let me have a quick think about a fix so it can work with V11 for now and I'll look at the next version being V12 only.

Cheers

**Comment by Genii-Locorum** [comment]
I've just put release v18 out which hopefully solves the problem - please let me know and if it works I'll close the issue.  

Cheers

**Comment by LeonxnoeL** [comment]
It works now! Thanks a ton.
