### ISSUE TITLE
combat opposed rolls imposible with npcs?

### ISSUE THREAD

**Issue by IoannesNuncius** [Genii-Locorum/brp#17]
I can't figure out how to complete the combat roll. the instructions seem outdated, since they say only to roll a dodge separately from the attack. Actually though, the attack roll will not go through without another party rolling against it.

Could be that I don't know how to use foundry, but nothing seems to be considered opposed to the attack roll except another weapon roll from the another character actor.

Is this a bug, or do I not know what I am doing?

**Comment by Genii-Locorum** [comment]
Heya - I'd completely forgotten about adding Dodge as part of a combat roll.  Yes, you can't complete an attack between two parties where one is dodging (a combat roll expects two parts of it)

I was wanting to take to some time to implement something like the  Call of Cthulhu ID system so I could identify a "dodge" skill irrespective of what it had been called - but this needs a quicker fix.  Let me have a play and see what I can do quickly

**Comment by Genii-Locorum** [comment]
@IoannesNuncius - ok here's a quick fix but would welcome your thoughts.

I've added "Dodge" skill (the skill will need to be named "Dodge" to the list of weapon skills (it's hard coded until I work on BRP IDs).  You then create a weapon called "Dodge" linked to the dodge skill.

Add the weapon to the actor and you can now dodge.

For NPCs I'd just create a weapon called Dodge with the relevant skill

![image](https://github.com/Genii-Locorum/brp/assets/121451824/9bd8145b-731e-4099-8009-1adf49cb555c)

**Comment by Genii-Locorum** [comment]
I separated them out to allow for damage rolls off the back of combat rolls (I've got these in Pendragon and Rivers of London) and for the potential to have more than 2 rolls in an opposed roll but cap the combat roll and 2 entries (I have these in Pendragon).

**Comment by IoannesNuncius** [comment]
Okay, it took me some playing around with this to understand what you meant. Now that I am more familiar with both foundry and brp I can see the virtue of your solution here. have you released this fix? I've updated, but there is still no dodge skill option when creating a new weapon.

Would it be possible to have the option of rolling any skill as a combat roll, similar to how Ctrl+m1 is an opposed roll? That would look cleaner in my opinion than a "Dodge" weapon.

**Comment by Genii-Locorum** [comment]
No worries - and always happy to answer questions.

I haven't released the fix yet - will try to sort it this weekend if I can find some time.

I could make it so any skill can be included in combat rolls - it would take some recoding - but if I was going to do that I'd rather spend the time sorting out the "IDs" so the weapon list can be generated without having to import everything from the compendiums (I want to do this so that whatever the dodge skill it can be added to combat roll whilst other skills cant).  Whilst it's a sticking plaster "dodge" as a weapon is easier - it was about 10 characters in the code.

I will reply here when I've made the update so hopefully you get notified.

**Comment by Genii-Locorum** [comment]
Heya - new version just released with Dodge fix in it.  The instructions are updated (a bit) and the Dodge weapon is in the compendium.
