### ISSUE TITLE
[BUG] Allegiances Bugs

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#20]
### Bug 1 - Characters
So when I added a new allegiance I noticed this boolean "false" that appears on the far right of the allegiance.

![image](https://github.com/user-attachments/assets/5a6c8428-5172-492b-ad10-197cfdd7f209)

It doesn't match the columns and nothing that I do seems to change it.

### Bug 2 - NPCS
Adding an allegiance on a NPC either from dropping it from the item directory or making a new one does make it appear. However when I type in a number there it resets to 0 no matter what I put there.

**Comment by Genii-Locorum** [comment]
Thank you - they will both be fixed in the next release (will see if there's some small changes I can make and roll out together).

The first true/false flag is the "potential Ally" flag - I forgot to remove it following some testing
Second issue I forgot to add the property to the npc.mjs file under Skill Edit.

If you want to manually make the second fix then change line 226 in npc.mjs to 

    if (['base','currHP','quantity','npcVal','allegPoints'].includes(field)) {

I won't close this issue until I've pushed the release out.

**Comment by Cosmic-Lattee** [comment]
Awesome thank you! :)

**Comment by Genii-Locorum** [comment]
Fixed in Version 12.1.24
