### ISSUE TITLE
[BUG] Sorcery Levels Set to Null

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#34]
Hello!

So a odd bug. When a player opens and closes a Sorcery spell the level vanishes. This does not happen when a GM opens and closes the spell.

![image](https://github.com/user-attachments/assets/6f8fbd58-7d6e-4197-af2f-6ccb4ee82011)

**Comment by Genii-Locorum** [comment]
Right, I think I figured this one out.  It was ultimately because the player can't edit the Max level so it didn't appear on the input form data that was being used to then check the Current and  Mem level didn't exceed the max level.  Fixed that so if it's a player then the Max Level is added to the form data.  Because the GM could edit the Max Level then it wasn't an issue.

Also made it so the player can toggle Memorised on/off from the item sheet.  Will go out in the next release.

**Comment by Genii-Locorum** [comment]
Now gone live with release 12.1.32
