### ISSUE TITLE
Request: ability to switch auto-tick from successes to failures

### ISSUE THREAD

**Issue by RevCivic** [Genii-Locorum/brp#42]
Just putting in a request to see if it would be possibly to switch the "auto tick" feature from success to failure with an option in the settings menu.

![image](https://github.com/user-attachments/assets/2d000def-795e-45c5-a416-5f4719d050b2)

Thanks

**Comment by Genii-Locorum** [comment]
Happy to have a look.  Just to clarify what you are you asking for - is this the autotick to happen on a failed roll rather than a success.  For each roll success level:
a) Critical Success
b) Special Success
c) Success
d) Fail
e) Fumble

what do you want the game to do
1) Add an XP tick
2) Do nothing
3) Remove an XP tick

Cheers

**Comment by RevCivic** [comment]
In this instance, if a fail (d) or fumble (e) were to occur, add an xp tick
to the associated skill.

It would be even better if there was an option for fumbles to reduce
sanity, but that feels like an additional request and I don't want to get
greedy.

Delta Green and Cthulu eternal follow the "fail to learn" method, and I
prefer that, but so far everything else about BRP has been working great.

Thank you!

**Comment by Genii-Locorum** [comment]
Will this do you?  It applies to all XP check - POW improvement, skills, traits etc.  

<img width="609" alt="image" src="https://github.com/user-attachments/assets/ab267ee1-37a6-433c-b9f8-8c39a01fda2b" />

**Comment by RevCivic** [comment]
Yes, that is perfect! Thank you!

**Comment by Genii-Locorum** [comment]
Included in release 12.1.36
